In [1]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from statistics import mean
from datetime import date, timedelta

In [2]:
months = 12
total_months = months * 2
end_date = date.today()
start_date = end_date - timedelta(days=(total_months-1)*30.5)

In [3]:

history_map = {}
for symbol in ['SMH', 'USD', 'SOXL', 'QQQ', 'TQQQ', 'NVDA', 'FNGU', 'FNGS', 'MAGS', 'MAGX', 'MAG7.L', 'NVD3.L', 'QQQ5.L',
               'MSFT', 'GOOGL', 'AMZN', 'AAPL', 'SPY', 'TSLA', 'IYW', 'XLKS.L']:
    tickerData = yf.Ticker(symbol)
    history = tickerData.history(interval='1d', start=start_date, end=end_date)
    consist = ((history.Low <= history.Open) & (history.Low <= history.Close) &
            (history.High >= history.Open) & (history.High >= history.Close))
    if not consist.all():
        print(f'WARN: {symbol} history: inconsistent price data!')
        display(history[~consist])
    # aggregate from daily to monthly data
    # for some symbols like QQQ5.L Yahoo monthly data is inconsistent
    history['Mid'] = history.Close
    history = history.resample('MS').agg({
        'Open': 'first',
        'High': 'max',
        'Low': 'min',
        'Close': 'last',
        'Mid': 'median'}) # use median to eliminate some glitches in the data
    if len(history) != total_months:
        print(
            f'WARN: {symbol} history: {len(history)}mo, {total_months}mo expected')
    history_map[symbol] = history

WARN: MAGS history: 17mo, 24mo expected
WARN: MAGX history: 7mo, 24mo expected
WARN: MAG7.L history: inconsistent price data!

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2024-04-09 00:00:00+01:00,18.885000,19.105000,18.000000,17.879999,71,0.0,0.0,0.0
2024-04-17 00:00:00+01:00,16.715000,17.360001,16.650000,16.312500,391,0.0,0.0,0.0
2024-07-01 00:00:00+01:00,31.459999,32.889999,30.280001,32.985001,15310,0.0,0.0,0.0
2024-07-11 00:00:00+01:00,49.130001,51.320000,42.200001,42.134998,58379,0.0,0.0,0.0
2024-07-19 00:00:00+01:00,32.490002,33.070000,31.000000,30.995001,29047,0.0,0.0,0.0

WARN: MAG7.L history: 5mo, 24mo expected
WARN: NVD3.L history: inconsistent price data!

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2022-09-21 00:00:00+01:00,0.430430,0.43467,0.404890,0.442070,218132,0.0,0.0,0.0
2022-10-03 00:00:00+01:00,0.336410,0.34457,0.303800,0.346850,113896,0.0,0.0,0.0
2022-10-13 00:00:00+01:00,0.254460,0.25446,0.212430,0.272390,325818,0.0,0.0,0.0
2022-10-19 00:00:00+01:00,0.272280,0.27391,0.269350,0.289180,575,0.0,0.0,0.0
2022-10-25 00:00:00+01:00,0.327610,0.37011,0.273930,0.370430,18216,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2024-01-11 00:00:00+00:00,9.945220,10.05087,9.396520,9.357390,55637,0.0,0.0,0.0
2024-01-15 00:00:00+00:00,10.000000,10.02609,9.981300,10.106740,13892,0.0,0.0,0.0
2024-01-18 00:00:00+00:00,10.852170,11.30391,10.852170,11.323040,82478,0.0,0.0,0.0
2024-02-12 00:00:00+00:00,21.780001,23.16478,21.714781,23.200871,78292,0.0,0.0,0.0
2024-03-01 00:00:00+00:00,27.320000,29.04565,26.567390,29.075871,62146,0.0,0.0,0.0

WARN: QQQ5.L history: inconsistent price data!

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2022-09-27 00:00:00+01:00,0.342,0.38423,0.33000,0.3275,63335,0.0,0.0,0.0
2022-10-07 00:00:00+01:00,0.333,0.33300,0.29000,0.2895,116097,0.0,0.0,0.0
2022-10-14 00:00:00+01:00,0.278,0.28200,0.25000,0.2495,70027,0.0,0.0,0.0
2022-10-25 00:00:00+01:00,0.308,0.33400,0.27828,0.3375,48817,0.0,0.0,0.0
2022-10-26 00:00:00+01:00,0.313,0.33700,0.30000,0.3380,79121,0.0,0.0,0.0
2022-10-28 00:00:00+01:00,0.262,0.28300,0.25700,0.3035,87038,0.0,0.0,0.0
2022-11-02 00:00:00+00:00,0.290,0.29000,0.27000,0.2690,189274,0.0,0.0,0.0
2022-11-08 00:00:00+00:00,0.238,0.26000,0.23018,0.2605,235938,0.0,0.0,0.0
2022-11-23 00:00:00+00:00,0.309,0.32900,0.30900,0.3295,91890,0.0,0.0,0.0
2022-11-29 00:00:00+00:00,0.306,0.32718,0.28100,0.2795,225433,0.0,0.0,0.0
2022-12-08 00:00:00+00:00,0.280,0.28100,0.27200,0.2890,112603,0.0,0.0,0.0

WARN: XLKS.L history: inconsistent price data!

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2022-09-27 00:00:00+01:00,301.869995,305.839996,301.869995,301.739990,532,0.0,0.0,0.0
2022-10-03 00:00:00+01:00,292.440002,298.070007,290.300110,298.329987,2680,0.0,0.0,0.0
2022-10-07 00:00:00+01:00,307.260010,307.940002,299.230011,299.114990,3312,0.0,0.0,0.0
2022-10-13 00:00:00+01:00,286.309998,289.406738,276.170013,289.619995,7251,0.0,0.0,0.0
2022-10-18 00:00:00+01:00,299.000000,302.100006,296.089996,294.959991,4317,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2024-04-30 00:00:00+01:00,546.400024,547.219971,544.760010,543.554993,954,0.0,0.0,0.0
2024-05-14 00:00:00+01:00,563.510010,566.070007,560.719971,566.414978,1057,0.0,0.0,0.0
2024-06-11 00:00:00+01:00,616.469971,620.169922,612.310120,620.239990,1607,0.0,0.0,0.0
2024-07-19 00:00:00+01:00,647.400024,648.900024,641.884216,641.770020,4220,0.0,0.0,0.0
2024-08-13 00:00:00+01:00,605.890015,616.799988,604.299988,616.905029,1875,0.0,0.0,0.0

In [4]:
rows = []
for symbol in history_map:
  history = history_map[symbol]
  # history['Mid'] = (history.Open + history.High + history.Low + history.Close) / 4
  history['Swing'] = (history.High - history.Low) * 2 / (history.High + history.Low)
  m = round(len(history) / 2)
  rows.append({
    'symbol': symbol,
    'history': len(history),
    'gain_norm': (history.Mid[m:].mean() / history.Mid[:m].mean() - 1) * total_months / len(history),
    'swing': history.Swing.mean(),
  })

data = pd.DataFrame(rows)
data['score'] = data.gain_norm / data.swing
print(data.sort_values(by='score', ascending=False))

    symbol  history  gain_norm     swing      score
11  NVD3.L       24  10.824785  0.691800  15.647265
5     NVDA       24   2.033038  0.236469   8.597490
1      USD       24   2.070549  0.332812   6.221370
6     FNGU       24   1.960424  0.378674   5.177077
7     FNGS       24   0.614967  0.127977   4.805284
20  XLKS.L       24   0.489652  0.107547   4.552904
8     MAGS       17   0.484581  0.108007   4.486583
0      SMH       24   0.656113  0.152567   4.300482
19     IYW       24   0.454483  0.106894   4.251706
9     MAGX        7   0.856129  0.207434   4.127233
12  QQQ5.L       24   1.627139  0.395850   4.110499
13    MSFT       24   0.437093  0.107916   4.050324
3      QQQ       24   0.367855  0.090963   4.044005
4     TQQQ       24   1.037164  0.269548   3.847793
10  MAG7.L        5   2.745502  0.717561   3.826160
17     SPY       24   0.234473  0.066231   3.540218
15    AMZN       24   0.500288  0.143649   3.482701
14   GOOGL       24   0.432029  0.132780   3.253709
2     SOXL       24   1.293485  0.442540   2.922863
16    AAPL       24   0.199907  0.113210   1.765798
18    TSLA       24   0.016499  0.270454   0.061006

In [5]:
display(history_map['NVD3.L'])

,Open,High,Low,Close,Mid,Swing
Date,,,,,,
2022-09-01 00:00:00+01:00,0.385650,0.444350,0.308700,0.346960,0.350275,0.360268
2022-10-01 00:00:00+01:00,0.336410,0.434780,0.212430,0.392450,0.317880,0.687103
2022-11-01 00:00:00+00:00,0.415650,0.718260,0.337500,0.566200,0.556035,0.721300
2022-12-01 00:00:00+00:00,0.688700,0.906090,0.346960,0.389570,0.612010,0.892430
2023-01-01 00:00:00+00:00,0.388260,0.994780,0.360330,0.878800,0.605760,0.936382
2023-02-01 00:00:00+00:00,0.872610,1.439570,0.872610,1.365870,1.180330,0.490412
2023-03-01 00:00:00+00:00,1.338700,2.127390,1.173480,2.094780,1.626520,0.577975
2023-04-01 00:00:00+01:00,2.130870,2.241300,1.831300,2.012170,1.961955,0.201346
2023-05-01 00:00:00+01:00,2.373040,5.936960,1.949710,4.916960,2.495760,1.011137
2023-06-01 00:00:00+01:00,4.740000,6.821740,4.302610,6.030430,5.662280,0.452904
2023-07-01 00:00:00+01:00,6.217390,8.609130,5.651740,7.879130,7.062390,0.414756
2023-08-01 00:00:00+01:00,7.895220,9.534780,4.960000,8.667830,6.899130,0.631231
2023-09-01 00:00:00+01:00,8.493910,8.801740,4.843480,5.809780,6.088260,0.580168
2023-10-01 00:00:00+01:00,5.954780,7.316960,3.952170,4.241520,5.806415,0.597169
2023-11-01 00:00:00+00:00,4.370430,8.268260,4.310430,6.435000,7.031415,0.629291
2023-12-01 00:00:00+00:00,6.452610,7.841300,5.693480,7.538480,6.989130,0.317378
2024-01-01 00:00:00+00:00,7.608700,14.966520,6.478260,13.487170,10.606305,0.791639
2024-02-01 00:00:00+00:00,14.021740,29.246960,13.846960,26.162170,22.129999,0.714718
2024-03-01 00:00:00+00:00,27.320000,47.642170,26.192490,37.071739,35.888700,0.581019
2024-04-01 00:00:00+01:00,36.276520,41.927090,20.748260,30.059349,30.717390,0.675826
2024-05-01 00:00:00+01:00,27.538700,1115.000000,24.782610,53.549999,36.532169,1.913027
2024-06-01 00:00:00+01:00,58.939999,113.650002,58.110001,77.349998,74.904999,0.646716
2024-07-01 00:00:00+01:00,73.940002,98.029999,39.599998,52.720001,69.709999,0.849088
2024-08-01 00:00:00+01:00,59.130001,60.209999,21.990000,57.630001,40.420000,0.929927